# Generated by Django 2.2.3 on 2019-08-01 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_auto_20190801_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservabr',
            name='reservante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReservBR', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservah',
            name='reservante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReservH', to=settings.AUTH_USER_MODEL),
        ),
    ]
