# Generated by Django 2.2.3 on 2019-08-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_auto_20190801_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fondos',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
