# Generated by Django 2.2.3 on 2019-08-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_auto_20190801_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservabr',
            name='restbar',
        ),
        migrations.RemoveField(
            model_name='reservah',
            name='hotel',
        ),
    ]
