# Generated by Django 2.2.3 on 2019-08-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_auto_20190801_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacidadbr',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='capacidadbr',
            name='restbar',
        ),
        migrations.RemoveField(
            model_name='capacidadh',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='capacidadh',
            name='hotel',
        ),
        migrations.AddField(
            model_name='capacidadbr',
            name='libre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capacidadbr',
            name='mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CapacidadBR', to='reserva.Mesa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacidadh',
            name='habitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CapacidadH', to='reserva.Habitacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capacidadh',
            name='libre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservah',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
