# Generated by Django 2.2.3 on 2019-08-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_auto_20190802_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacidadh',
            name='libre',
            field=models.BooleanField(default=True),
        ),
    ]
