# Generated by Django 2.2.3 on 2019-08-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_auto_20190802_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacidadbr',
            name='libre',
            field=models.BooleanField(default=True),
        ),
    ]
