# Generated by Django 2.2.3 on 2019-08-05 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0011_auto_20190802_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='dueño',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Dueñoh', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restbar',
            name='dueño',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Dueñob', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
