# Generated by Django 2.2.3 on 2019-08-06 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0012_auto_20190805_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('libre', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discobar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=55)),
                ('ciudad', models.CharField(blank=True, max_length=55)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dueñod', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MesaD',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('capacidad', models.IntegerField()),
                ('discobar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MesaD', to='reserva.Discobar')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaReserva', models.DateTimeField(auto_now_add=True)),
                ('diaReservado', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('mesad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReservaHab', to='reserva.MesaD')),
                ('reservante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReservH', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='dueño',
        ),
        migrations.RemoveField(
            model_name='reservah',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='reservah',
            name='reservante',
        ),
        migrations.DeleteModel(
            name='CapacidadH',
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='ReservaH',
        ),
        migrations.AddField(
            model_name='capacidadd',
            name='mesad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CapacidadH', to='reserva.MesaD'),
        ),
    ]
